### ISSUE TITLE
Error while parsing URL

### ISSUE THREAD

**Issue by masonshuler** [mmw125/MuDimA#12]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/newspaper/parsers.py", line 54, in fromstring
    cls.doc = lxml.html.fromstring(html)
  File "/Library/Python/2.7/site-packages/lxml/html/__init__.py", line 706, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/Library/Python/2.7/site-packages/lxml/html/__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src/lxml/lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:102470)
  File "parser.pxi", line 1667, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:101229)
  File "parser.pxi", line 1035, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:96139)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91904)
XMLSyntaxError: line 396: Element script embeds close tag
You must download and parse an article before parsing it!

It seems like there is an issue with the article URLs. Not all URLs will be valid and they throw this specific error. I will look more into it before assigning a fix.

**Comment by masonshuler** [comment]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/newspaper/parsers.py", line 54, in fromstring
    cls.doc = lxml.html.fromstring(html)
  File "/Library/Python/2.7/site-packages/lxml/html/__init__.py", line 706, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/Library/Python/2.7/site-packages/lxml/html/__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src/lxml/lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:102470)
  File "parser.pxi", line 1667, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:101229)
  File "parser.pxi", line 1035, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:96139)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91904)
XMLSyntaxError: line 758: Tag footer invalid
You must download and parse an article before parsing it!

Tag footer invalid bug might be the cause. Still looking into it.

**Comment by mmw125** [comment]
I noticed this as well when doing some testing a couple weeks ago and haven't noticed it since then. It was strange since it gave me that error after I had already downloaded and parsed it.

**Comment by masonshuler** [comment]
I am having the same problem when trying to replicate it. It is not showing up. I am going to try to test all of the top headline urls and see if a specific one is causing the issue for all of them.

**Comment by masonshuler** [comment]
The synopsis is that certain websites provide faulty XML code. Such as  usatoday.com. The parser throws errors when this happens.

**Comment by masonshuler** [comment]
The suggestion is to remove usatoday.com, rgj.com, and vice.com from the supported sources to parse as they consistently throw errors.

**Comment by mmw125** [comment]
We could do that, however I don't really want to go through the work of maintaining a black list for sites that we don't support. Also, I think it works fine right now. Since its catching the exception so the program will not crash. When the exception is caught it sets the keywords for the article to an empty set. Then when the classifier is run, it skips grouping any articles that don't have any keywords. This will prevent it from getting written to the database. One problem with this however, is that with #21 it will keep thinking that the url is new. This is good if article ever gets updated with a format that we can read however, I think the chance of that happening in which case we are just fetching the article every update while it is in top headlines for no real reason. One way to fix this would be to store them in the database without a grouping id so that they would be marked as already being in the database.
