### ISSUE TITLE
OperationalError: table article has no column named date

### ISSUE THREAD

**Issue by masonshuler** [mmw125/MuDimA#29]
When calling localhost/updateStories table is not updated because:

OperationalError: table article has no column named date

[2017-10-23 00:38:21,809] ERROR in app: Exception on /updateStories [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 17, in update_stories
    news_fetcher.update_database()
  File "/Users/mshuler/Documents/MuDimA/server/news_fetcher.py", line 67, in update_database
    database_writer.write_topics_to_database(grouped)
  File "/Users/mshuler/Documents/MuDimA/server/database_writer.py", line 21, in write_topics_to_database
    grouping.get_uuid()))
OperationalError: table article has no column named date
127.0.0.1 - - [23/Oct/2017 00:38:23] "GET /updateStories HTTP/1.0" 500 -

**Comment by mmw125** [comment]
Try deleting your database

**Comment by masonshuler** [comment]
I did,

    def setUp(self):
        """Set up the class for the tests."""
        self._database_name_mock = mock.patch("server.database_utils.database_name", return_value="mudima_test.db")
        self._database_name_mock.start()
        self._database_location = database_utils.database_path(database_utils.database_name())
        self._delete_database()

    def tearDown(self):
            """Tear down the class for the tests."""
            self._delete_database()
            self._database_name_mock.stop()

    def _delete_database(self):
            if os.path.exists(self._database_location):
                os.remove(self._database_location)

    def test_update_stories_then_get_everything(self):
        self.assertEqual(0, len(database_reader.get_urls()))
        wget.download('http://127.0.0.1:80/updateStories')
        url_len = len(database_reader.get_urls())
        assert 0 < url_len <-- this assert fails bc 0 < 0

**Comment by mmw125** [comment]
Have you pulled in the newest master? Because that column was added in #21

**Comment by masonshuler** [comment]
Pushed to branch server-tests

Run app.py in the background then run py.test

**Comment by mmw125** [comment]
Tested on master. All tests pass when running app.py
